logging:
  level:
    com.mlestyan: info

server:
  port: 9090

spring:
  application:
    name: document-service
  messages:
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:doctype-dict
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

document:
  application:
    document-types-json-file-path: kodszotar46_okmanytipus.json
  validation:
    document-number-validation-patterns:
      1: "[0-9]{6}[A-Z]{2}"
      2: "[A-Z]{2}[0-9]{7}"
      3: "[A-Z]{2}[0-9]{6}"
    max-document-number-length: 10
    supported-image-formats:
    - JPG
    - JPEG
    image-width: 827
    image-height: 1063
eureka:
  client:
    enabled: false

---
spring:
  profiles: discovery
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://service-discovery-service:8761/eureka}