spring:
  messages:
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:state-dict
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
person:
  application:
    state:
      state-json-file-path: kodszotar21_allampolg.json
    document:
      api:
        url: http://localhost:9090
        document-complete-path: /complete-document
  validation:
    min-age: 18
    max-age: 120
    max-name-length: 80
    expected-nationality-character-count: 3
server:
  port: 8080
eureka:
  client:
    enabled: false

---
spring:
  profiles: discovery
  application:
    name: person-service
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://service-discovery-service:8761/eureka}
