
server.port: 9080

spring:
  messages:
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:state-dict
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

person:
  application:
    state:
      state-json-file-path: kodszotar21_allampolg.json
    document:
      api:
        url: http://localhost:9090
        document-complete-path: /complete-document
  validation:
    min-age: 18
    max-age: 120
    max-name-length: 80
    expected-nationality-character-count: 3